language: node_js
node_js:
- 6.11.2
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install: yarn install
script: yarn run test
deploy:
  provider: npm
  email: npmjs+eng@eventbrite.com
  on:
    tags: true
    repo: eventbrite/britecharts-react
